### ISSUE TITLE
PSNU Names Not Populating in Column B Disagg Tool for Zambia Test

### ISSUE THREAD

**Issue by bowdenj** [achafetz/DataPack#142]
Hi @achafetz - I copied Zambia's Allocation by SNUxIM tab into the Disagg Tool tab, clicking into cell C7 and pasting as values. However, it looks like the only cell in column B that populated was B7 (_military Zambia). There were no additional PSNUs that populated, even though the formula does go all the way to the last row. Expected?

**Comment by achafetz** [comment]
This is a formatting issue I haven't been able to shake. If you take a close look, you'll see that all of the cells are populated, they just appear blank on the screen due to the cell formatting (;;;). If you change the cell formatting to General it will appear. Still trying to figure out how to stop this from happening.

**Comment by bowdenj** [comment]
@achafetz you're right --switched to General for those cells and they populated immediately. 

Just did a cursory search, and it looks like it might help to save these as an Excel Template (.xltx). Found basic info here: https://www.vitalyst.com/2011/03/productivity-101-setting-up-excel-default-formatting/ 
Not sure if you've already tried that, but worth a shot if this is continuing to happen

**Comment by achafetz** [comment]
thanks! looks like I was able to get it to work by completely clearing out all of the content and removing all formatting and adding it back in.
