### ISSUE TITLE
Calculations for TB_ART in Moz non-HTS disag tool

### ISSUE THREAD

**Issue by pvinayak001** [achafetz/DataPack#146]
File name: MozambiqueCOP18DisaggToolv2018.02.01.xlsx

I'm unclear on how the calculations are done for TB_ART disags. In Row 39 (green), 84 * 45%=38, and 84 * 55%=46 as I would expect. But in row 33 (yellow) 52 * 35%=18.2, but value shown is 40 (Disagg: already) and 52 * 11%=5.7, but value shown is 12 (Disagg: new on treatment).

![image](https://user-images.githubusercontent.com/22644265/36035489-106bd834-0d85-11e8-930a-783208fdb105.png)

**Comment by pvinayak001** [comment]
IM names removed for security.

**Comment by achafetz** [comment]
Thanks, @pvinayak001. I think this is confusing since the Data Pack is also calculating disaggs.

Essentially the allocations are mutliplies by the DP targets to get the disagg targets. ART Status actually is no longer a target, so there are no associated targets with it, just age. In the version you are looking at, there the ART Status allocations are just sitting there, not being used for anything.

I removed it on Wednesday to cut down on confusion. 

Here a more current version - https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/WORKSTREAMS/Data%20Pack/Development/Beta%20Packs/Kenya2018.02.09.zip
