### ISSUE TITLE
Formatting Kenya non-HTS disag tool

### ISSUE THREAD

**Issue by pvinayak001** [achafetz/DataPack#147]
File name:KenyaCOP18DisaggToolv2018.02.08.xlsx
Tab: PMTCT_STAT
Columns: AV-AW

100% is formatted red in some rows but not others due to rounding (99.99% gets rounded to 100% but still shows up red). May want to change the formula so >99.5 shows up black or change the rounding so that it's clear that percentages don't fully add up to 100%.

**Comment by achafetz** [comment]
Excellent point. One issue is that the formatting is built into the number format rather than conditional formatting (makes it much easier and is more efficient processing wise). The other issue is that when their percent is 99.5% I want them to go int and figure out the last 0.5% so they don't "lose" people I've added additional rounding the percent to slightly help with this issue.

![image](https://user-images.githubusercontent.com/8933069/36269508-5e72765c-1247-11e8-82ba-246add3f2093.png)
